# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HomebrewMason < Formula
  desc "Binary distribution using homebrew."
  homepage "https://github.com/cirbuk/homebrew-mason"
  version "0.1.4"

  on_macos do
    url "https://github.com/cirbuk/homebrew-mason/releases/download/v0.1.4/homebrew-mason_0.1.4_darwin_x86_64.tar.gz"
    sha256 "7c3bbd28466466f2f54f4fcd6d7d40809c208d5114060b1d3a34f4078b028c13"

    def install
      bin.install "homebrew-mason"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the HomebrewMason
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cirbuk/homebrew-mason/releases/download/v0.1.4/homebrew-mason_0.1.4_linux_x86_64.tar.gz"
      sha256 "c1da4dfbafa70ffaa81763d4ed2f1947d643116059a63fcd9cc12242d557e739"

      def install
        bin.install "homebrew-mason"
      end
    end
  end
end
