# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HomebrewMason < Formula
  desc "Binary distribution using homebrew."
  homepage "https://github.com/cirbuk/homebrew-mason"
  version "0.1.2"

  on_macos do
    url "https://github.com/cirbuk/homebrew-mason/releases/download/v0.1.2/homebrew-mason_0.1.2_darwin_x86_64.tar.gz"
    sha256 "4e12614c341ff51ba8e912f429d53f8eec4f9035f8eec9924329ff6a27494741"

    def install
      bin.install "homebrew-mason"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the HomebrewMason
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cirbuk/homebrew-mason/releases/download/v0.1.2/homebrew-mason_0.1.2_linux_x86_64.tar.gz"
      sha256 "a575002fdf0f743c2b409723ae3aa39379b3aa1c25a268004c18e598586b7156"

      def install
        bin.install "homebrew-mason"
      end
    end
  end
end
