# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mason < Formula
  desc "Binary distribution using homebrew."
  homepage "https://github.com/cirbuk/mason-cli"
  version "0.1.16"

  on_macos do
    url "https://github.com/cirbuk/mason-cli/releases/download/v0.1.16/mason-cli_0.1.16_darwin_x86_64.tar.gz"
    sha256 "a4cda4a635dc16e584751dc2da5fc8f65a3e70b4e6966b8cf5f89aac80cc7993"

    def install
      bin.install "mason"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Mason
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cirbuk/mason-cli/releases/download/v0.1.16/mason-cli_0.1.16_linux_x86_64.tar.gz"
      sha256 "ae204ff75926208c36463696415302a3f81467452ecd10d8cea82df7596b27bf"

      def install
        bin.install "mason"
      end
    end
  end
end
