# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mason < Formula
  desc "Binary distribution using homebrew."
  homepage "https://github.com/cirbuk/mason-cli"
  version "0.1.14"

  on_macos do
    url "https://github.com/cirbuk/mason-cli/releases/download/v0.1.14/mason-cli_0.1.14_darwin_x86_64.tar.gz"
    sha256 "ad12de6c000debac545b83c0eed42853b2501b7a377cc4fb224b08b09efe4757"

    def install
      bin.install "mason"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Mason
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cirbuk/mason-cli/releases/download/v0.1.14/mason-cli_0.1.14_linux_x86_64.tar.gz"
      sha256 "d43650352e5dd5266b607cb8c775e9b4b3081314c705550c045b52527f4ae1bc"

      def install
        bin.install "mason"
      end
    end
  end
end
