# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mason < Formula
  desc "Binary distribution using homebrew."
  homepage "https://github.com/cirbuk/homebrew-mason"
  version "0.1.6"

  on_macos do
    url "https://github.com/cirbuk/homebrew-mason/releases/download/v0.1.6/homebrew-mason_0.1.6_darwin_x86_64.tar.gz"
    sha256 "3baadf29c2011082a2ddf9e47d8e3e40a9ef5feb1c8672a513b9f9245b38e6f5"

    def install
      bin.install "mason"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Mason
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cirbuk/homebrew-mason/releases/download/v0.1.6/homebrew-mason_0.1.6_linux_x86_64.tar.gz"
      sha256 "bec2e9dcb658f9f9b0500115e7599c0ce1f6104299e7c5c13702962bcf9bb934"

      def install
        bin.install "mason"
      end
    end
  end
end
